{"flood_version":"0.3.1","dependency_versions":{"ctc":"0.3.9","ipykernel":"6.29.0","ipython_genutils":"0.2.0","matplotlib":"3.8.2","nbconvert":"6.5.4","nbformat":"5.9.2","numpy":"1.23.5","orjson":"3.9.10","pdp":"0.2.2","polars":"0.17.15","requests":"2.30.0","toolcli":"0.6.16","toolplot":"0.3.5","toolstr":"0.9.8","tqdm":"4.65.0","typing_extensions":null},"cli_args":["/Users/apoorvsadana/.pyenv/versions/3.9.16/bin/flood","eth_getLogs","NODE1_NAME=http://localhost:8545","--rates","200","--duration","2","-o","."],"type":"single_test","t_run_start":1710940185.8626509,"t_run_end":1710940189.16504,"nodes":{"NODE1_NAME":{"name":"NODE1_NAME","url":"http://localhost:8545","remote":null,"client_version":null,"network":"ethereum"}},"results":{"NODE1_NAME":{"target_rate":[200],"actual_rate":[200.47646148003244],"target_duration":[2],"actual_duration":[1.995246709],"requests":[400],"throughput":[0],"success":[0.0],"min":[0.000107458],"mean":[0.000405456],"p50":[0.000329938],"p90":[0.000580895],"p95":[0.000714395],"p99":[0.001288395],"max":[0.007308917],"status_codes":[{"0":400}],"errors":[["Post \"http://localhost:8545\": dial tcp 0.0.0.0:0->[::1]:8545: connect: connection refused","Post \"http://localhost:8545\": dial tcp 0.0.0.0:0->127.0.0.1:8545: connect: connection refused"]],"first_request_timestamp":["2024-03-20T18:39:47.11697575+05:30"],"last_request_timestamp":["2024-03-20T18:39:49.112222459+05:30"],"last_response_timestamp":["2024-03-20T18:39:49.113485292+05:30"],"final_wait_time":[0.001262833],"deep_raw_output":null,"deep_metrics":null,"deep_rpc_error_pairs":null}}}